language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install coveralls
before_script:
    - psql -c 'create database sendit;' -U postgres
script:
    - pytest
    - coverage run -m pytest
after_success:
    - coveralls
services:
    - postgresql

